name: Nick
author: DaOnlySonic
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8]
version: 1.0.2
main: Nick\Main
commands:
 nick:
  description: Gives the sender a Nickname
  permission: nick

permissions:
 nick:
  description: Permission to allow setting nicknames
  default: op
