name: Nick
author: DaOnlySonic
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8]
version: 1.0.1
main: Sonic\Nick\Main
commands:
 nick:
  description: "Nick Command"
  aliases: [Nick]
permissions:
nick:
default: op
children:
nick.set
description: "Nick set command permission"
default: op
nick.see
description: "Nick see command permission"
default: op
